# mixed-port: 7890
# redir-port: 7892
# tproxy-port: 7893
# external-controller: 9090
# allow-lan: true
# ipv6: false
# mode: Rule
# log-level: info
# dns:
#   enable: true
#   ipv6: false
#   listen: 0.0.0.0:53
#   enhanced-mode: redir-host
#   use-hosts: true
#   nameserver:
#     - 1.2.4.8
#     - 223.5.5.5
#   # GEOIP 非 CN 走 fallback 解析
#   fallback:
#     - https://1.1.1.1/dns-query
#   fallback-filter:
#     geoip: true
#     geoip-code: CN
#     ipcidr:
#       - 240.0.0.0/4
#     domain:
#       - +.google.com
#       - +.github.com
#       - +.youtube.com
#       - +.duckduckgo.com